dinesh/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :details
  root 'details#index'

end

dinesh/app/models/detail.rb
class Detail < ActiveRecord::Base
end

dinesh/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

dinesh/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

dinesh/app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /details
  # GET /details.json
  def index
    @details = Detail.all
  end

  # GET /details/1
  # GET /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1
  # PATCH/PUT /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to details_url, notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_params
      params.require(:detail).permit(:name, :age, :email, :school)
    end
end

dinesh/app/helpers/application_helper.rb
module ApplicationHelper
end

dinesh/app/helpers/details_helper.rb
module DetailsHelper
end

dinesh/app/views/details/_form.html.erb
<%= form_for(@detail) do |f| %>
  <% if @detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% @detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dinesh/app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

dinesh/app/views/details/index.html.erb
<h1>Listing details</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>School</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr>
        <td><%= detail.name %></td>
        <td><%= detail.age %></td>
        <td><%= detail.email %></td>
        <td><%= detail.school %></td>
        <td><%= link_to 'Show', detail %></td>
        <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
        <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detail', new_detail_path %>

dinesh/app/views/details/new.html.erb
<h1>New detail</h1>

<%= render 'form' %>

<%= link_to 'Back', details_path %>

dinesh/app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @detail.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @detail.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @detail.email %>
</p>

<p>
  <strong>School:</strong>
  <%= @detail.school %>
</p>

<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>

dinesh/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dinesh</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>